// sw.js — Service Worker for PWA + Firebase Push Notifications
const CACHE_NAME = 'kafeel-v1';

// ─── Firebase config (injected at build time) ─────────────────
// sw-config.js is generated by generate-env.js and is gitignored.
// It sets self.KAFEEL_FIREBASE_CONFIG and self.KAFEEL_VAPID_KEY.
// If the file doesn't exist (no Firebase config set), FCM is skipped.
try { importScripts('sw-config.js'); } catch (e) {}

const _fbConfig = (typeof self.KAFEEL_FIREBASE_CONFIG !== 'undefined')
  ? self.KAFEEL_FIREBASE_CONFIG : null;

// ─── Firebase Messaging (Background Push) ────────────────────
if (_fbConfig) {
  try {
    importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
    importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

    firebase.initializeApp(_fbConfig);
    const messaging = firebase.messaging();

    // Handle push when the app is NOT in the foreground
    messaging.onBackgroundMessage((payload) => {
      const title = payload.notification?.title || 'ماركت الكفيل';
      const body  = payload.notification?.body  || '';
      return self.registration.showNotification(title, {
        body,
        icon:    'assets/kafeel_icon.png',
        badge:   'assets/kafeel_icon.png',
        tag:     'kafeel-order-' + Date.now(),
        vibrate: [200, 100, 200],
        data:    payload.data || {},
      });
    });
  } catch (e) {
    console.warn('[SW] Firebase init failed:', e);
  }
}

// ─── Install / Activate ──────────────────────────────────────
self.addEventListener('install', () => self.skipWaiting());

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then(names => Promise.all(
        names.filter(n => n !== CACHE_NAME).map(n => caches.delete(n))
      ))
      .then(() => clients.claim())
  );
});

// ─── Notification click — focus or open the app ───────────────
self.addEventListener('notificationclick', (e) => {
  e.notification.close();
  e.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
      for (const c of list) {
        if (c.url.includes('/index.html') || c.url.endsWith('/')) return c.focus();
      }
      return clients.openWindow('/');
    })
  );
});

// ─── Cache (Network-first) ───────────────────────────────────
self.addEventListener('fetch', (e) => {
  const url = e.request.url;
  if (
    url.includes('supabase.co') ||
    url.includes('googleapis.com') ||
    url.includes('gstatic.com') ||
    e.request.method !== 'GET'
  ) return;

  e.respondWith(
    fetch(e.request)
      .then(res => {
        if (res.status === 200) {
          const clone = res.clone();
          caches.open(CACHE_NAME).then(c => c.put(e.request, clone));
        }
        return res;
      })
      .catch(() => caches.match(e.request))
  );
});
